"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"

type Language = "pl" | "ua" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  pl: {
    "header.main": "Strona główna",
    "header.pickup": "Miejsce Odbioru",
    "header.bikes": "Rowery",
    "header.contact": "Kontakt",
    "header.signup": "Zarejestruj się",
    "header.login": "Zaloguj się",
    "header.logout": "Wyloguj się",
    "header.openingHours": "Godziny otwarcia",
    "header.openingHoursBadge": "Pon-Pt 09:00-18:00",
    "hero.headline": "Odkrywaj Miasto na Rowerze",
    "hero.subheadline": "Wypożyczaj nowoczesne rowery bez kaucji. Szybka rezerwacja, doskonały serwis.",
    "hero.cta": "Rezerwuj teraz",
    "hero.badge_available": "Dostępne rowery",
    "hero.badge_unavailable": "Brak wolnych rowerów",
    "advantages.title": "Nasze Zalety",
    "advantages.transparentPrices": "Transparentne ceny",
    "advantages.transparentPricesDesc": "1 dzień - 50 zł, 1 tydzień - 180 zł, 1 miesiąc - 720 zł",
    "advantages.maintenance": "Serwis wliczony",
    "advantages.maintenanceDesc": "Całkowity serwis i konserwacja w cenie",
    "advantages.equipment": "Pełne wyposażenie",
    "advantages.equipmentDesc": "Kłódka, uchwyt do telefonu, ładowarka, bateria",
    "advantages.comfort": "Komfort i wszechstronność",
    "advantages.comfortDesc": "Idealny dla kurierów i transportu miejskiego",
    "advantages.flexible": "Elastyczne warunki",
    "advantages.flexibleDesc": "Opcje dzienne, tygodniowe i miesięczne",
    "advantages.safety": "Bezpieczeństwo i niezawodność",
    "advantages.safetyDesc": "Sprawdzenie techniczne przed każdym wynajmem",
    "howItWorks.title": "Jak to działa?",
    "howItWorks.step1": "Zarezerwuj online",
    "howItWorks.step1Desc": "Zarezerwuj rower na naszej stronie w kilka minut",
    "howItWorks.step2": "Odebrać rower",
    "howItWorks.step2Desc": "Przybądź do naszej wypożyczalni i odebrać swój rower",
    "howItWorks.step3": "Jeżdż i ciesz się!",
    "howItWorks.step3Desc": "Ciesz się jazdą po mieście",
    "bikes.title": "Nasze rowery",
    "bikes.choose": "Wybierz idealny rower dla siebie",
    "bikes.city": "Rower miejski",
    "bikes.mountain": "Rower górski",
    "bikes.wheels": "Koła",
    "bikes.brakes": "Hamulce",
    "bikes.motor": "Silnik",
    "bikes.battery": "Bateria",
    "bikes.day": "Dzień",
    "bikes.week": "Tydzień",
    "bikes.month": "Miesiąc",
    "bikes.availability": "Dostępny",
    "bikes.book": "Rezerwuj",
    "bikes.unavailable": "Niedostępny",
    "bikes.soldOut": "Wyprzedane",
    "reviews.title": "Opinie klientów",
    "reviews.leaveReview": "Zostaw opinię",
    "reviews.loginReview": "Zaloguj się, aby zostawić opinię",
    "faq.title": "Często zadawane pytania",
    "faq.q1": "Jakie są warunki wynajmu?",
    "faq.a1":
      "Oferujemy wynajmy dzienne (1 dzień - 50 zł), tygodniowe (1 tydzień - 180 zł) i miesięczne (1 miesiąc - 720 zł).",
    "faq.q2": "Co jest wliczone?",
    "faq.a2": "Serwis, bateria, ładowarka, uchwyt do telefonu i kłódka - wszystko wliczone w cenę.",
    "faq.q3": "Czy potrzebna jest kaucja?",
    "faq.a3": "Nie! Brak kaucji, tylko umowa wynajmu.",
    "faq.q4": "Czy mogę przedłużyć wynajm?",
    "faq.a4": "Tak! Możesz przedłużyć wynajm, skontaktuj się z nami.",
    "faq.q5": "Co w przypadku awarii?",
    "faq.a5": "Darmowy remont, jeśli awaria nie jest wynikiem winy użytkownika.",
    "faq.q6": "Czy mogę wynająć rower do celów kurierskich?",
    "faq.a6": "Tak! Nasze rowery są idealne dla kurierów i dostarczaczy.",
    "faq.q7": "Gdzie odbierze rower?",
    "faq.a7": "Warszawa, ul. Karmelicka 3CF - to nasza główna lokalizacja.",
    "faq.q8": "Jaki jest limit wiekowy?",
    "faq.a8": "Wymagane są co najmniej 18 lat.",
    "faq.q9": "Jaki jest zasięg baterii?",
    "faq.a9": "Zasięg baterii to 60-80 km na jednym ładowaniu.",
    "faq.q10": "Czy kask jest wliczony?",
    "faq.a10": "Kaski są rekomendowane i dostępne za dodatkową opłatę 10 zł.",
    "faq.q11": "Jaki jest czas zwrotu?",
    "faq.a11":
      "W przypadku wynajmu dziennego - tego samego dnia. W przypadku długoterminowych - ostatniego dnia wynajmu.",
    "faq.q12": "Czy mogę wynająć dodatkową baterię?",
    "faq.a12": "Tak! Dodatkowa bateria kosztuje 50 zł.",
    "faq.q13": "Co jeśli dostanę dziurkę w oponach?",
    "faq.a13": "Możesz naprawić sam lub zadzwonić do nas na płatną usługę.",
    "contact.call": "Zadzwoń do nas",
    "contact.telegram": "Telegram",
    "footer.contactTitle": "Kontakt",
    "footer.about": "Nowoczesna wypożyczalnia rowerów elektrycznych. Szybko, wygodnie, ekologicznie i bez kaucji.",
    "footer.navTitle": "Nawigacja",
    "footer.address": "ul. Karmelicka 3CF, Warszawa",
    "footer.phone": "+48 12 345 67 89",
    "footer.email": "info@rowerrent.pl",
    "footer.rights": "Wszelkie prawa zastrzeżone.",
    "footer.terms": "Regulamin",
    "footer.privacy": "Polityka Prywatności",
    "legal.termsTitle": "Regulamin",
    "legal.termsContent":
      "Tu będzie treść regulaminu...\n\n1. Warunki ogólne\nWypożyczenie roweru podlega następującym warunkom:\n- Renter musi mieć co najmniej 18 lat\n- Wymagane jest okazanie dokumentu tożsamości\n- Renter odpowiada za stan roweru podczas wynajmu\n\n2. Opłaty\nOpłaty za wynajem są ściśle określone w formularzu rezerwacji.\n\n3. Ograniczenie odpowiedzialności\nNie ponosimy odpowiedzialności za wypadki spowodowane niedopatrzeniem rentiera.\n\n4. Zmian tego regulaminu\nZastrzegamy sobie prawo do zmiany regulaminu bez powiadomienia.",
    "legal.privacyTitle": "Polityka Prywatności",
    "legal.privacyContent":
      "Tu będzie treść polityki prywatności...\n\n1. Zbieranie danych\nZbieramy dane osobowe w celu obsługi wynajmu rowerów.\n\n2. Wykorzystanie danych\nTwoje dane są używane wyłącznie do celów wynajmu i komunikacji.\n\n3. Ochrona danych\nZastosowujemy standardowe zabezpieczenia do ochrony Twoich danych.\n\n4. Prawa użytkownika\nMasz prawo do dostępu, zmiany lub usunięcia swoich danych na żądanie.\n\n5. Kontakt\nW przypadku pytań dotyczących prywatności, skontaktuj się z nami pod adresem info@rowerrent.pl",
    "legal.close": "Zamknij",
    "registration.title": "Utwórz konto",
    "registration.firstName": "Imię",
    "registration.lastName": "Nazwisko",
    "registration.phone": "Numer telefonu",
    "registration.email": "Email (Login)",
    "registration.password": "Hasło",
    "registration.passwordHint": "Minimum 8 znaków, litery i cyfry",
    "registration.submit": "Zarejestruj się",
    "registration.close": "Zamknij",
    "registration.termsLabel": "Akceptuję ",
    "registration.termsLink": "Regulamin",
    "registration.termsAnd": " i ",
    "registration.privacyLink": "Politykę Prywatności",
    "booking.termsLabel": "Akceptuję ",
    "booking.termsLink": "Regulamin",
    "booking.termsAnd": " i ",
    "booking.privacyLink": "Politykę Prywatności",
    "login.processing": "Przetwarzanie...",
    "login.title": "Zaloguj się",
    "login.email": "Email",
    "login.password": "Hasło",
    "login.submit": "Zaloguj się",
    "login.cancel": "Anuluj",
    "registration.successTitle": "Rejestracja powiodła się!",
    "registration.successMessage": "Rejestracja powiodła się! Zaloguj się za pomocą swoich danych uwierzytelniających.",
    "reviews.writeReview": "Napisz opinię",
    "review.title": "Zostaw opinię",
    "review.rating": "Twoja ocena",
    "review.comment": "Komentarz",
    "review.placeholder": "Podziel się swoją opinią o wypożyczalni...",
    "review.cancel": "Anuluj",
    "review.submit": "Wyślij opinię",
    "review.submitting": "Wysyłanie...",
  },
  ua: {
    "header.main": "Головна",
    "header.pickup": "Місце отримання",
    "header.bikes": "Велосипеди",
    "header.contact": "Контакти",
    "header.signup": "Реєстрація",
    "header.login": "Вхід",
    "header.logout": "Вихід",
    "header.openingHours": "Час роботи",
    "header.openingHoursBadge": "Пн-Пт 09:00-18:00",
    "hero.headline": "Досліджуй місто на велосипеді",
    "hero.subheadline":
      "Орендуйте сучасні велосипеди без депозиту. Швидке бронювання, чудовий сервіс.",
    "hero.cta": "Забронювати",
    "hero.badge_available": "Доступні велосипеди",
    "hero.badge_unavailable": "Немає в наявності",
    "advantages.title": "Наші переваги",
    "advantages.transparentPrices": "Прозорі ціни",
    "advantages.transparentPricesDesc": "1 день - 50 зл, 1 тиждень - 180 зл, 1 місяць - 720 зл",
    "advantages.maintenance": "Сервіс включений",
    "advantages.maintenanceDesc": "Повне обслуговування та технічне обслуговування в ціну",
    "advantages.equipment": "Повне обладнання",
    "advantages.equipmentDesc": "Замок, тримач для телефону, зарядний пристрій, батарея",
    "advantages.comfort": "Комфорт та універсальність",
    "advantages.comfortDesc": "Ідеально для кур'єрів та міського транспорту",
    "advantages.flexible": "Гнучкі умови",
    "advantages.flexibleDesc": "Щоденні, тижневі та місячні варіанти",
    "advantages.safety": "Безпека та надійність",
    "advantages.safetyDesc": "Технічна перевірка перед кожною орендою",
    "howItWorks.title": "Як це працює?",
    "howItWorks.step1": "Забронювати онлайн",
    "howItWorks.step1Desc": "Забронюйте велосипед на нашому сайті за кілька хвилин",
    "howItWorks.step2": "Взяти велосипед",
    "howItWorks.step2Desc": "Приходьте в нашу прокатню і отримайте свій велосипед",
    "howItWorks.step3": "Їздити і насолоджуватися!",
    "howItWorks.step3Desc": "Насолоджуйтесь їздою по місту",
    "bikes.title": "Наші велосипеди",
    "bikes.choose": "Виберіть ідеальний велосипед для себе",
    "bikes.city": "Міський велосипед",
    "bikes.mountain": "Гірський велосипед",
    "bikes.wheels": "Колеса",
    "bikes.brakes": "Гальма",
    "bikes.motor": "Двигун",
    "bikes.battery": "Акумулятор",
    "bikes.day": "День",
    "bikes.week": "Тиждень",
    "bikes.month": "Місяць",
    "bikes.availability": "Доступний",
    "bikes.book": "Забронювати",
    "bikes.unavailable": "Недоступний",
    "bikes.soldOut": "Розпродано",
    "reviews.title": "Відгуки клієнтів",
    "reviews.leaveReview": "Залишити відгук",
    "reviews.loginReview": "Увійдіть, щоб залишити відгук",
    "faq.title": "Часті запитання",
    "faq.q1": "Які умови оренди?",
    "faq.a1":
      "Ми пропонуємо щоденну орендування (1 день - 50 зл), тижневу (1 тиждень - 180 зл) та місячну (1 місяць - 720 зл).",
    "faq.q2": "Що включено?",
    "faq.a2": "Сервіс, акумулятор, зарядний пристрій, тримач для телефону та замок - все включено в ціну.",
    "faq.q3": "Чи потрібен депозит?",
    "faq.a3": "Ні! Без депозиту, тільки договір оренди.",
    "faq.q4": "Чи можу я продовжити оренду?",
    "faq.a4": "Так! Ви можете продовжити орендування, зв'яжіться з нами.",
    "faq.q5": "Що робити при поломці?",
    "faq.a5": "Безплатний ремонт, якщо поломка не є виною користувача.",
    "faq.q6": "Чи можу я орендувати велосипед для кур'єрської роботи?",
    "faq.a6": "Так! Наші велосипеди ідеальні для кур'єрів та доставників.",
    "faq.q7": "Де я можу отримати велосипед?",
    "faq.a7": "Київ, вул. Кармеликька 3CF - це наша основна локація.",
    "faq.q8": "Яка вікова межа?",
    "faq.a8": "Потрібно мати щонайменше 18 років.",
    "faq.q9": "Який запас ходу батареї?",
    "faq.a9": "Запас ходу батареї становить 60-80 км на одній зарядці.",
    "faq.q10": "Чи шолом включено?",
    "faq.a10": "Шоломи рекомендовані та доступні за додаткову плату 10 зл.",
    "faq.q11": "Який час повернення?",
    "faq.a11": "Для щоденної оренди - в той же день. Для довгострокових - в останній день оренди.",
    "faq.q12": "Чи можу я орендувати додаткову батарею?",
    "faq.a12": "Так! Додаткова батарея коштує 50 зл.",
    "faq.q13": "Що якщо у мене проколота шина?",
    "faq.a13": "Ви можете самостійно відремонтувати або зателефонуйте нам за платну послугу.",
    "contact.call": "Зателефонуйте нам",
    "contact.telegram": "Telegram",
    "footer.about": "Сучасний прокат електровелосипедів. Швидко, зручно, екологічно та без застави.",
    "footer.navTitle": "Навігація",
    "footer.contactTitle": "Контакти",
    "footer.address": "вул. Кармеликька 3CF, Київ",
    "footer.phone": "+380 44 123 45 67",
    "footer.email": "info@rowerrent.ua",
    "footer.rights": "Всі права захищені.",
    "footer.terms": "Положення",
    "footer.privacy": "Політика конфіденційності",
    "legal.termsTitle": "Положення",
    "legal.termsContent":
      "Тут буде вміст положення...\n\n1. Загальні умови\nОренда велосипеда підпорядковується таким умовам:\n- Орендатор повинен бути не молодшим за 18 років\n- Вимагається показати документ, що посвідчує особу\n- Орендатор несе відповідальність за стан велосипеда під час оренди\n\n2. Збори\nПлата за оренду суворо визначена у формі бронювання.\n\n3. Обмеження відповідальності\nМи не несемо відповідальності за нещасні випадки, спричинені недбалістю орендатора.\n\n4. Зміни цих положень\nМи залишаємо за собою право змінювати положення без попередження.",
    "legal.privacyTitle": "Політика конфіденційності",
    "legal.privacyContent":
      "Тут буде вміст політики конфіденційності...\n\n1. Збір даних\nМи збираємо персональні дані з метою обслуговування оренди велосипедів.\n\n2. Використання даних\nТвої дані використовуються виключно для цілей оренди та спілкування.\n\n3. Захист даних\nМи застосовуємо стандартні заходи безпеки для захисту твоїх даних.\n\n4. Права користувача\nТи маєш право доступу, зміни або видалення своїх даних за запитом.\n\n5. Контакт\nЯкщо у вас є запитання щодо конфіденційності, зв'яжіться з нами за адресою info@rowerrent.ua",
    "legal.close": "Закрити",
    "registration.title": "Створити обліковий запис",
    "registration.firstName": "Ім'я",
    "registration.lastName": "Прізвище",
    "registration.phone": "Номер телефону",
    "registration.email": "Email (Логін)",
    "registration.password": "Пароль",
    "registration.passwordHint": "Мінімум 8 символів, букви та цифри",
    "registration.submit": "Зареєструватися",
    "registration.close": "Закрити",
    "registration.termsLabel": "Приймаю ",
    "registration.termsLink": "Положення",
    "registration.termsAnd": " і ",
    "registration.privacyLink": "Політику конфіденційності",
    "booking.termsLabel": "Приймаю ",
    "booking.termsLink": "Положення",
    "booking.termsAnd": " і ",
    "booking.privacyLink": "Політику конфіденційності",
    "login.processing": "Обробка...",
    "login.title": "Входити",
    "login.email": "Email",
    "login.password": "Пароль",
    "login.submit": "Входити",
    "login.cancel": "Скасувати",
    "registration.successTitle": "Реєстрація успішна!",
    "registration.successMessage": "Реєстрація успішна! Увійдіть, використовуючи свої облікові дані.",
    "reviews.writeReview": "Написати відгук",
    "review.title": "Залишити відгук",
    "review.rating": "Ваша оцінка",
    "review.comment": "Коментар",
    "review.placeholder": "Поділіться своєю думкою про прокатню...",
    "review.cancel": "Скасувати",
    "review.submit": "Надіслати відгук",
    "review.submitting": "Надсилання...",
  },
  en: {
    "header.main": "Home",
    "header.pickup": "Pickup Location",
    "header.bikes": "Bikes",
    "header.contact": "Contact",
    "header.signup": "Sign Up",
    "header.login": "Log In",
    "header.logout": "Log Out",
    "header.openingHours": "Opening Hours",
    "header.openingHoursBadge": "Mon-Fri 09:00-18:00",
    "hero.headline": "Explore the City by Bike",
    "hero.subheadline": "Rent modern bikes with no deposit. Quick booking, excellent service.",
    "hero.cta": "Book Now",
    "hero.badge_available": "Available bikes",
    "hero.badge_unavailable": "Sold Out",
    "advantages.title": "Our Advantages",
    "advantages.transparentPrices": "Transparent Prices",
    "advantages.transparentPricesDesc": "1 day - 50 zl, 1 week - 180 zl, 1 month - 720 zl",
    "advantages.maintenance": "Maintenance Included",
    "advantages.maintenanceDesc": "Full maintenance and service included in price",
    "advantages.equipment": "Full Equipment",
    "advantages.equipmentDesc": "Lock, phone holder, charger, battery included",
    "advantages.comfort": "Comfort & Versatility",
    "advantages.comfortDesc": "Perfect for delivery and city commuting",
    "advantages.flexible": "Flexible Terms",
    "advantages.flexibleDesc": "Daily, weekly and monthly options",
    "advantages.safety": "Safety & Reliability",
    "advantages.safetyDesc": "Technical check before every rental",
    "howItWorks.title": "How It Works",
    "howItWorks.step1": "Book Online",
    "howItWorks.step1Desc": "Book a bike on our website in a few minutes",
    "howItWorks.step2": "Pick Up",
    "howItWorks.step2Desc": "Come to our bike shop and pick up your bike",
    "howItWorks.step3": "Ride & Enjoy",
    "howItWorks.step3Desc": "Enjoy riding around the city",
    "bikes.title": "Our Bikes",
    "bikes.choose": "Choose the perfect bike for you",
    "bikes.city": "City Bike",
    "bikes.mountain": "Mountain Bike",
    "bikes.wheels": "Wheels",
    "bikes.brakes": "Brakes",
    "bikes.motor": "Engine",
    "bikes.battery": "Battery",
    "bikes.day": "Day",
    "bikes.week": "Week",
    "bikes.month": "Month",
    "bikes.availability": "Available",
    "bikes.book": "Book",
    "bikes.unavailable": "Unavailable",
    "bikes.soldOut": "Sold Out",
    "reviews.title": "Customer Reviews",
    "reviews.leaveReview": "Leave a Review",
    "reviews.loginReview": "Please log in to leave a review",
    "faq.title": "Frequently Asked Questions",
    "faq.q1": "What are the rental conditions?",
    "faq.a1": "We offer daily rental (1 day - 50 zl), weekly (1 week - 180 zl) and monthly (1 month - 720 zl).",
    "faq.q2": "What's included?",
    "faq.a2": "Maintenance, battery, charger, phone holder and lock - everything included in the price.",
    "faq.q3": "Is there a deposit?",
    "faq.a3": "No! No deposit, just a rental contract.",
    "faq.q4": "Can I extend the rental?",
    "faq.a4": "Yes! You can extend the rental, contact us.",
    "faq.q5": "What if there's a breakdown?",
    "faq.a5": "Free repair if the breakdown is not the user's fault.",
    "faq.q6": "Can I rent for delivery use?",
    "faq.a6": "Yes! Our bikes are perfect for couriers and delivery riders.",
    "faq.q7": "Where is the pickup location?",
    "faq.a7": "Warsaw, Karmelicka Street 3CF - this is our main location.",
    "faq.q8": "What is the age limit?",
    "faq.a8": "You must be at least 18 years old.",
    "faq.q9": "What is the battery life?",
    "faq.a9": "Battery range is 60-80 km on a single charge.",
    "faq.q10": "Is the helmet included?",
    "faq.a10": "Helmets are recommended and available for an extra fee of 10 zl.",
    "faq.q11": "What is the return time?",
    "faq.a11": "For daily rental - same day. For long-term - last day of rental.",
    "faq.q12": "Can I rent an extra battery?",
    "faq.a12": "Yes! Extra battery costs 50 zl.",
    "faq.q13": "What if I get a flat tire?",
    "faq.a13": "You can fix it yourself or call us for a paid service.",
    "contact.call": "Call Us",
    "contact.telegram": "Telegram",
    "footer.about": "Modern electric bike rental. Fast, convenient, eco-friendly and no deposit.",
    "footer.navTitle": "Navigation",
    "footer.contactTitle": "Contacts",
    "footer.address": "Karmelicka Street 3CF, Warsaw",
    "footer.phone": "+48 12 345 67 89",
    "footer.email": "info@rowerrent.com",
    "footer.rights": "All rights reserved.",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "legal.termsTitle": "Terms of Service",
    "legal.termsContent":
      "This is the placeholder content for terms of service...\n\n1. General Conditions\nBike rental is subject to the following conditions:\n- Renter must be at least 18 years old\n- A valid ID document is required\n- Renter is responsible for the bike's condition during rental\n\n2. Fees\nRental fees are strictly defined in the booking form.\n\n3. Limitation of Liability\nWe are not responsible for accidents caused by renter negligence.\n\n4. Changes to Terms\nWe reserve the right to change these terms without notice.",
    "legal.privacyTitle": "Privacy Policy",
    "legal.privacyContent":
      "This is the placeholder content for privacy policy...\n\n1. Data Collection\nWe collect personal data for the purpose of managing bike rentals.\n\n2. Data Usage\nYour data is used solely for rental purposes and communication.\n\n3. Data Protection\nWe apply standard security measures to protect your data.\n\n4. User Rights\nYou have the right to access, modify, or delete your data upon request.\n\n5. Contact\nIf you have any privacy questions, contact us at info@rowerrent.com",
    "legal.close": "Close",
    "registration.title": "Create Account",
    "registration.firstName": "First Name",
    "registration.lastName": "Last Name",
    "registration.phone": "Phone Number",
    "registration.email": "Email (Login)",
    "registration.password": "Password",
    "registration.passwordHint": "Minimum 8 characters, letters and numbers",
    "registration.submit": "Register",
    "registration.close": "Close",
    "registration.termsLabel": "I accept ",
    "registration.termsLink": "Terms of Service",
    "registration.termsAnd": " and ",
    "registration.privacyLink": "Privacy Policy",
    "booking.termsLabel": "I accept ",
    "booking.termsLink": "Terms of Service",
    "booking.termsAnd": " and ",
    "booking.privacyLink": "Privacy Policy",
    "login.processing": "Processing...",
    "login.title": "Log In",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Log In",
    "login.cancel": "Cancel",
    "registration.successTitle": "Registration Successful!",
    "registration.successMessage": "Registration successful! Please log in using your credentials.",
    "reviews.writeReview": "Write a Review",
    "review.title": "Leave a Review",
    "review.rating": "Your Rating",
    "review.comment": "Comment",
    "review.placeholder": "Share your experience with us...",
    "review.cancel": "Cancel",
    "review.submit": "Submit Review",
    "review.submitting": "Submitting...",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("pl")

  const t = (key: string): string => {
    return translations[language]?.[key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}

export default LanguageProvider

